# Generated by Django 6.0.4 on 2026-04-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubs_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serving_size', models.CharField(choices=[('pint', 'Pint'), ('half', 'Half'), ('third', 'Third')], default='pint', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pint_logs', to='pints.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pint_logs', to=settings.AUTH_USER_MODEL)),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pint_logs', to='pints.pub')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
