# Generated by Django 6.0.4 on 2026-04-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
