# Generated by Django 5.1.7 on 2026-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pints', '0002_beer_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintlog',
            name='is_seeded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='beer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pintlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
