# Generated by Django 5.1.7 on 2026-04-22 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pints', '0005_seed_amenities_and_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pint', 'Price & Pint'), ('amenity', 'Added Amenity'), ('event', 'Added Event'), ('confirmation', 'Confirming')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('amenity_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='pints.amenityreport')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='pints.event')),
                ('event_confirmation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='pints.eventconfirmation')),
                ('pint_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='pints.pintlog')),
                ('pub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='pints.pub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pints_contr_user_id_008133_idx'), models.Index(fields=['kind', '-created_at'], name='pints_contr_kind_0f8f48_idx')],
            },
        ),
    ]
